### ISSUE TITLE
As Developer I want to see Open Issue and Resolved Issue

### ISSUE THREAD

**Issue by huseyinbuyukdere** [aantipov/moiva#445]
Hi ! , Moiva is really good and basic. Comparing, searching packages are nice too. But I couldn't see the open issues or 
closed issues of package and the charts below the compare table maybe can be better. 

![image](https://user-images.githubusercontent.com/39594189/128509606-e28890ac-2a5e-4c45-bcb2-63efb30b8303.png)

Maybe I can contirubute it for you about these problems, If I can do.

**Comment by aantipov** [comment]
Hi @huseyinbuyukdere, 
Do you want to see the total number of open issues and the total number of closed issues?

>and the charts below the compare table maybe can be better.

what exactly do you suggest to improve?

**Comment by huseyinbuyukdere** [comment]
@aantipov yes, I want to see the total number of open issues and the closed issues, 

For chart, I said about only Maintenance and Development Activity .  you can change the data which you show, because npm releases, contributors or commit counts are not crucial things for me and event data is unstable to say something . Number of open issues or closed issues data are better to say something about packages.

**Comment by aantipov** [comment]
Why is the number of open/closed issues matters to you and how one can compare packages based on those figures?

I intentionally didn't add those numbers because to me they provide subtle value:
- they are a function of multiple unrelated factors: library's age, popularity, documentation quality, etc.
- there are many different types of issues (bugs, feature requests, questions, documentation, etc.) and summation of all of them tells me nothing about the library/package.

I'm closing the issue now.
However, I'm open to any additional discussion if reasonable counter-arguments are given

Thank you for your feedback!
